[tool.poetry]
name = "aramislab-handbook"
version = "0.0.1"
description = "The ARAMIS Lab Handbook"
authors = ["Ghislain Vaillant <ghislain.vaillant@icm-institute.org>"]
license = "CC-BY-SA-4.0"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
